require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# needed for unimodules :
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0' #11.0 instead of 10.0 needed for unimodules

target 'streamo' do
  # in addition to all the documented steps for unimodules, I had to add the following podspec paths :
  pod 'UMFontInterface', :path => '../node_modules/unimodules-font-interface/ios'
  pod 'UMFileSystemInterface', :path => '../node_modules/unimodules-file-system-interface/ios'
  pod 'UMCameraInterface', :path => '../node_modules/unimodules-camera-interface/ios'

  # needed for unimodules
  use_unimodules!(exclude: [
    'expo-constants',
    'expo-file-system',
    'expo-image-loader',
    'expo-permissions',
    'unimodules-app-loader',
    'unimodules-barcode-scanner-interface',
    'unimodules-camera-interface',
    'unimodules-constants-interface',
    'unimodules-face-detector-interface',
    'unimodules-file-system-interface',
    'unimodules-font-interface',
    'unimodules-image-loader-interface',
    'unimodules-permissions-interface',
    'unimodules-sensors-interface',
    'unimodules-task-manager-interface',    
  ])

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'streamoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

  # needed for react-native-osc
  # use_frameworks!
end

target 'streamo-tvOS' do
  # Pods for streamo-tvOS

  target 'streamo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
